version: "3.9"
services:

  node_red_vue:
    build: .

    networks:
      - node_red_vue

    ports:
      - "1880:1880"
      - "3000:3000"

    environment:
      DB_USER: root
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: demo

      HOVEDNØGLE: ${HOVEDKEY}

      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"

      # Express miljøvariabler
      VUE_PORT: 3000
      BACKEND_URL: http://localhost:1880
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.

      TZ: "Europe/Copenhagen"

    volumes:
      - "./node-red/:/data" 
      
    depends_on: 
      - redis_microservice  
      - db

  redis_microservice:
    build:
      context: ./redis_microservice
    networks:
      - node_red_vue

  python_microservice:
    build:
      context: ./python_queue_microservice
    networks:
      - node_red_vue
    depends_on:
      - redis_microservice
  
  db:
    image: mariadb:10.6.11
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: demo
      TZ: "Europe/Copenhagen"

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=pass
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

    networks:
      - node_red_vue
      
networks: 
  node_red_vue:
    name: node_red_vue
